//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexusat.AspNetCore.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nexusat.AspNetCore.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BuilderInvalidStateAlreadyUsed {
            get {
                return ResourceManager.GetString("BuilderInvalidStateAlreadyUsed", resourceCulture);
            }
        }
        
        internal static string IApiResponseInternalNotImplemented {
            get {
                return ResourceManager.GetString("IApiResponseInternalNotImplemented", resourceCulture);
            }
        }
        
        internal static string StatusCodeInvalid {
            get {
                return ResourceManager.GetString("StatusCodeInvalid", resourceCulture);
            }
        }
        
        internal static string StatusOkCodeInvalid {
            get {
                return ResourceManager.GetString("StatusOkCodeInvalid", resourceCulture);
            }
        }
        
        internal static string StatusKoCodeInvalid {
            get {
                return ResourceManager.GetString("StatusKoCodeInvalid", resourceCulture);
            }
        }
        
        internal static string SubCodeInvalidFormat {
            get {
                return ResourceManager.GetString("SubCodeInvalidFormat", resourceCulture);
            }
        }
        
        internal static string InvalidStatePaginationCursor {
            get {
                return ResourceManager.GetString("InvalidStatePaginationCursor", resourceCulture);
            }
        }
        
        internal static string InvalidItemsCount {
            get {
                return ResourceManager.GetString("InvalidItemsCount", resourceCulture);
            }
        }
        
        internal static string PaginationIndexMustBePositive {
            get {
                return ResourceManager.GetString("PaginationIndexMustBePositive", resourceCulture);
            }
        }
        
        internal static string PaginationSizeMustBeNonNegative {
            get {
                return ResourceManager.GetString("PaginationSizeMustBeNonNegative", resourceCulture);
            }
        }
        
        internal static string PaginationIndexMustEqualsOneInCaseOfPageSizeZero {
            get {
                return ResourceManager.GetString("PaginationIndexMustEqualsOneInCaseOfPageSizeZero", resourceCulture);
            }
        }
        
        internal static string InvalidUriTooManyQuestionMarks {
            get {
                return ResourceManager.GetString("InvalidUriTooManyQuestionMarks", resourceCulture);
            }
        }
        
        internal static string NoRoutesMatched {
            get {
                return ResourceManager.GetString("NoRoutesMatched", resourceCulture);
            }
        }
    }
}
